### ISSUE TITLE
Additional VCS packages needed

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/php-docker#26]
This is a followup issue to #18 .

Composer supports several different VCS drivers (listed [here](https://github.com/composer/composer/tree/master/src/Composer/Repository/Vcs)).

Git was introduced in #18, but the remaining VCS packages should be included into the images as well.

**Comment by tmatsuo** [comment]
I'm still wondering whether we should install mercurial and subversion since those are minor choices. At the same time, we run composer.sh in ONBUILD section, so there's no way for users to install those software before we run composer for now.

Options are:

1. Just install mercurial and subversion
2. If there is a shell script with a specific name (e.x. before_onbuild.sh or whatever), run them at the very begining of our ONBUILD section. Users can have a shell script which installs mercurial and/or subversion if necessary.

I'm inclined to the option 2 above because, anyways we will need to have such a feature if we want to support installing arbitrary extensions based on the contents of the `composer.json`. Users can install runtime libraries which are required by the extensions. For example, to install `imagick` extension you will need to install `libmagickwand-6.q16-2` and `libmagickcore-6.q16-2` to use it and you also need `libmagickcore-6.q16-dev` and `libmagickwand-6.q16-dev` for compiling, and so on.

(For library installation like that, we can also have a simple database for needed apt packages for extensions.)

What do you think guys?

**Comment by JustinBeckwith** [comment]
Why not both?  I'm tempted to just install mercurial and subversion.  It would be kind of hard to figure out on your own what's happening, and I'd rather composer install 'just work'.  What are the downsides (aside from image size)?

On the before_build.sh script - this is something I've wanted to do in a standard way across runtimes for a while.  The biggest reason we avoided it was the fact that it completely blows up docker build caching.  But if we're using ONBUILD, it doesn't really matter anyway.  

I'd say lets start with adding hg/svn.

**Comment by tmatsuo** [comment]
Ok. The additional image size of installing hg/svn is 20mb or so. Let's install hg and svn.
