### ISSUE TITLE
Private Repository in composer.json with gcloud auth

### ISSUE THREAD

**Issue by iamacarpet** [GoogleCloudPlatform/php-docker#263]
We have some private libraries that are included using composer as private repositories.

```json
  "repositories": [
    {
      "type": "git",
      "url": "https://source.developers.google.com/p/..../r/..."
    }
  ]
```
Initially, we were using our private BitBucket hosting for these, but being built remotely meant the authentication was unavailable.

Since the container builder already runs in the context of a service account that has Editor access to the project [1], would you consider a pull request where gcloud was installed and the git authentication helper configured before the composer update was run?

It would be a good compromise for us to be able to use the private Google Cloud repositories.

Regards,
iamacarpet

[1]: https://cloud.google.com/container-builder/docs/permissions

**Comment by tmatsuo** [comment]
@iamacarpet Yeah pull request welcome! The automate test will fail (because circleci won't have our service account key), but don't worry, if the code LGTM, we'll move the PR to our repo so that we can run the test.

**Comment by iamacarpet** [comment]
@tmatsuo Thanks, that's great :). A little bit of bad news though, in that I built a copy of the runtime with the "gcloud" tool installed, but it didn't really help as it looks like the credentials described [here](https://cloud.google.com/container-builder/docs/permissions) aren't exposed inside the Container Builder runtime, instead just used by it to pull/access resources outside of the build process.

Cloud Support are trying to find out some more information for me to confirm, will keep you posted.

**Comment by iamacarpet** [comment]
@tmatsuo It looks like the automatic authentication isn't going to happen in the short term, but as a replacement, would you be willing to accept manually including a service account JSON file?

When testing, composer wouldn't checkout a private repository unless it has a writable home directory to cache into, so I ended up changing the call to it to include the prefix "`HOME=/app`".

What do you think about keeping that plus setting
`GOOGLE_APPLICATION_CREDENTIALS=/app/.composer/gcloud_auth.json`
and including some instructions on creating a service account and dropping the JSON here?

Having the "`.composer`" folder will mean people can also include "`.composer/auth.json`" with credentials for other custom Git repository locations, as well as the Google hosted ones.

**Comment by tmatsuo** [comment]
@iamacarpet 

Overall, I understand what you're trying to do. I see 2 fundamental problems here.

1. environment variable
The big problem within the current build process is that, `composer`can not see the env variable in `app.yaml`. Because we're using ONBUILD instructions for executing composer. We're planning to stop using ONBUILD, and will likely convert `env_variables` into `ENV` instructions in the final `Dockerfile`. This way, whatever env variables set in `app.yaml` will be available to all the build processes, and the runtime.

2. writable home directory
I got your point. We'll think about setting `HOME = ${APP_DIR}` for composer execution.

That's our current plan.

I feel hesitant to always set `GOOGLE_APPLICATION_CREDENTIALS` because it will affect subsequent library calls, and it's quite confusing.

**Comment by iamacarpet** [comment]
Thanks @tmatsuo, I'll hold off until you have made the build process changes, as I suppose there's not much point including the gcloud tool if there's no way to authenticate it at the moment.

I agree that would have been confusing, glad you've got a much better idea :).

After doing some research about using our existing self-hosted BitBucket so we don't have to move anything, they suggested SSH which we could hopefully make use of with the `HOME = ${APP_DIR}` change and including a `.ssh` directory, so it would be great if that was still considered even while the gcloud stuff was a blocker :).

**Comment by tmatsuo** [comment]
My current plan:

1. Create /opt/composer, make it writable to www-data, and set ${COMPOSER_HOME} pointing to /opt/composer
2. Remove `--no-script` from `composer install`
3. Pass all the env_variables in `app.yaml` to the build process

I think it will unblock your use case. We'll notify here once the new build pipeline is available.

**Comment by tmatsuo** [comment]
@iamacarpet We've silently launch a new build pipeline which might unblock you.

The changes with the new build pipeline are:
1. It passes `env_variables` in `app.yaml` to the build process
1. The docker image has $COMPOSER_HOME set to /opt/composer which is writable by `www-data`
1. Removed `--no-script` for `composer install`

To use the new pipeline
1. run `gcloud config set app/use_runtime_builders true`
2. use `gcloud beta app` for deployment

Keep in mind that, the new pipeline still uploads `app.yaml` to the container, so don't forget to use a proper `document_root`, otherwise your app.yaml will be served publicly.

**Comment by tmatsuo** [comment]
The new pipeline is the default behavior with the new google cloud sdk release (166 or higher).

Marking this as fixed
