### ISSUE TITLE
PECL install fails when extending the runtime

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/php-docker#367]
I get the following error when trying to run `pecl install`:

```
Step 3/4 : RUN pecl install pthreads
 ---> Running in 77064be783ca
// ...
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.
```

Here is my Dockerfile:

```
FROM gcr.io/google_appengine/php

# Custom PECL installation
RUN pecl install pthreads
```

It's fixable if I add the following right before it:

```
RUN apt-get install -y autoconf build-essential
```

Is there a way users can quickly install unsupported extensions and specific versions of supported extensions?

**Comment by tmatsuo** [comment]
We don't use `--enable-maintainer-zts` for compile PHP, which means you can not use `pthreads` extension anyways.

To answer the question, you're right. Now you have to have a custom `Dockerfile` to install extensions which we don't offer. We'd like to support custom build step in the near future though.

FWIW, we started to compile almost all stable extensions (see the list at https://cloud.google.com/appengine/docs/flexible/php/runtime), so I hope the issue is somewhat mitigated.

**Comment by bshaffer** [comment]
Yes, I was just using `pthreads` to test PECL. I eventually hit the ZTS issue, and that's ok because that's specific to pthreads. I am assuming at this point, other compatible extensions and extension versions will work.
