### ISSUE TITLE
Is this ready for production use?

### ISSUE THREAD

**Issue by dmarklund** [GoogleCloudPlatform/php-docker#93]
I just found this and I'd love to test it out. Is it ready for production use?

**Comment by cedricziel** [comment]
I'm in no way affiliated with Google but have contributed some PRs and use the image virtually since day 1 with the goal of riding it through to production.

To answer your question: As always, I'd say 'It depends'.

I've found it to be quite stable and we use it in a staging service. One thing that hit me was some sort of garbage collection. Every 12 hours or so, the load (for 2 mostly idling g1 instances) goes to 140% CPU which makes for 1 or 2 cloud monitoring alerts each day without increased requests count. 

Apart from that there's a few things I don't think the image is to blame for. It's quite oppinionated and that's a good thing in some way.

There's a few things happening in the near past that make me think the PHP flex runtime is close to a release, but the image doesn't provide stable tags (yet) so you may not (or maybe never) be able to properly version the underlying service versions apart from commit hashes.

I'm pretty confident in the image though and can't wait to see how it performs under real load.

**Comment by dmarklund** [comment]
@cedricziel Thanks for the reply and clarification. I might give this a try later on. I do hope that GAE updates their runtimes for PHP so we can use PHP 7.x as a default environment though! Don't really get why they haven't at least updated it to 5.9.

**Comment by cedricziel** [comment]
The standard runtime performs fantastically well-but the restrictions don't really fit modern PHP as you can't predict whether a 3party library uses forbidden/disabled functions and if you want to write to the filesystem as part of some upfront caching you're in bad luck.

I don't think they'll ever update the standard runtime. Flex runtimes need at least 2 instances for zero downtime services - that means the cost for the customer is significantly higher than with the standard runtimes.

**Comment by JustinBeckwith** [comment]
Greetings folks!  It's great to hear that this is working out for some folks.  As it stands today, this image is still *experimental*.  As we mention on the README, it's not covered by any SLA or deprecation policy. It may change at any time.  While you're free to use it (and we even have documentation that covers using it), it is not even at the alpha release stage quite yet.  That having been said - we tend to keep up with PRs, we're still working on the image, and we fully intend to get this up to a full release - it's just not there quite yet :)

**Comment by bshaffer** [comment]
Hello @dmarklund et. al.!

This runtime is officially in `alpha`. Check out [the product page](https://cloud.google.com/appengine/docs/flexible/php/) for more information. Testing purposes is perfectly fine, per the disclaimer:

> This is an Alpha release of the PHP runtime, which means that this release is not feature complete, no SLAs are provided, and there are no technical support obligations, but it is far enough along that you can use it in test environments or for limited-use tests. 

Closing this, but please comment back with any questions!
